packages:
  - packages/*
  - docs
  - play
  - internal/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  puppeteer: true
  vue-demi: true

overrides:
  jwa: ^1.4.2 # 20697
  typescript: $typescript

patchedDependencies:
  async-validator@4.2.5: patches/async-validator@4.2.5.patch #16757

peerDependencyRules:
  ignoreMissing:
    - vite
    - react
    - react-dom

shellEmulator: true
strictPeerDependencies: false
