export const PKG_PREFIX = '@element-plus'
export const PKG_NAME = 'element-plus-mobile'
export const PKG_CAMELCASE_NAME = 'ElementPlusMobile'
export const PKG_CAMELCASE_LOCAL_NAME = 'ElementPlusMobileLocale'
export const PKG_BRAND_NAME = 'Element Plus Mobile'
